

# ===============================
# PORT Render
# ===============================
server.port=${PORT:8083}
server.address=0.0.0.0
# ===============================
# DB (Render env vars)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-orange-tooth-ancu363n.c-6.us-east-1.aws.neon.tech/database_smartv2_26z1?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EVhy8iqbDrw3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# JWT (Render env vars)
# ===============================
bezkoder.app.jwtSecret=JWT_SECRET=peaceSecuritySecretKey123456789123456789123456
bezkoder.app.jwtExpirationMs=86400000
# ===============================
# MAIL (Render env vars)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8



