package com.king.pos.enums;

public enum TypeMouvementStock {
     ENTREE_ACHAT,
    VENTE,
    AJUSTEMENT,
    CASSE,
    INVENTAIRE,
    RETOUR_CLIENT,
    SORTIE_VENTE,
    SORTIE_AJUSTEMENT,
    ENTREE_AJUSTEMENT,
    TRANSFERT_ENTREE,
    TRANSFERT_SORTIE,
    AJUSTEMENT_INVENTAIRE_ENTREE,
    AJUSTEMENT_INVENTAIRE_SORTIE,
    VENTE_SORTIE,
    INVENTAIRE_ENTREE,
    INVENTAIRE_SORTIE,
    AJUSTEMENT_ENTREE,
    AJUSTEMENT_SORTIE,
    RETOUR_CLIENT_ENTREE,
    RETOUR_FOURNISSEUR_SORTIE,
    ANNULATION_VENTE_ENTREE,
    ANNULATION_RECEPTION_SORTIE
}
