package com.king.pos.enums;

public enum TypeTransactionStock {
    ACHAT_ENTREE,
    VENTE_SORTIE,
    INVENTAIRE_ENTREE,
    INVENTAIRE_SORTIE,
    AJUSTEMENT_ENTREE,
    AJUSTEMENT_SORTIE,
    RETOUR_CLIENT_ENTREE,
    RETOUR_FOURNISSEUR_SORTIE,
    TRANSFERT_SORTIE,
    TRANSFERT_ENTREE,
    ANNULATION_VENTE_ENTREE,
    ANNULATION_RECEPTION_SORTIE
}
